### ISSUE TITLE
It is possible to add close method?

### ISSUE THREAD

**Issue by pastukhov** [flochtililoch/ifttt-wordpress-webhook#1]
Hi, i'm trying to create ifttt webhook node for node-red framework. 
It initing all the objects after rules deployed. So i'm getting EADDRINUSE.

**Comment by flochtililoch** [comment]
hi,
I'm not sure what the close method would do, could you detail?
I'm guessing you are using the default configuration, which tries to open the port 80 to expose the XMLRPC server that IFTTT will hit. Since you are getting the error `EADDRINUSE`, this port must be already taken on your host, so you can change the configuration as following:

```javascript
...
var params = {
  ...
  server: {
    host: 'localhost',
    path: '/xmlrpc.php',
    port: <choose a port number here>
  }
};

server = iftttWebHook(params);
```

**Comment by pastukhov** [comment]
No, i'm not using default configuration.
The problem is in that node-red will reinit each node after redeploy the
flows and each node should close all the ports/devices. So, i need close
xmlrpc server when node-red this.on('close', is invoked.

Without it i'm getting second instance of xmltpc server on same port.
17 июня 2015 г. 18:30 пользователь "Florent" <notifications@github.com>
написал:

**Comment by flochtililoch** [comment]
Got it.
The instance returned by `iftttWebHook` helper is a `node-xmlrpc` server instance, which [implements the close method](https://github.com/baalexander/node-xmlrpc/blob/master/lib/server.js#L68-L71). You should be able to simply call `server.close()` on node-red close event.

**Comment by pastukhov** [comment]
Im using 3000 port to bind and node-red use 1883 port itself.

Everything is fine after first deploy, but port is keeping open after
second deploy and second instance of ifttt-wordpress-webhook will bind same
port.
I need to have posibility to stop port listening.
 17 июня 2015 г. 18:30 пользователь "Florent" <notifications@github.com>
написал:

**Comment by flochtililoch** [comment]
did you try [my suggestion above](#issuecomment-112930443)?

**Comment by pastukhov** [comment]
Not yet.
Y have no idea how to do this.
17 июня 2015 г. 23:15 пользователь "Florent" <notifications@github.com>
написал:

**Comment by flochtililoch** [comment]
basically something like this:

```javascript
...

server = iftttWebHook(params);

...
nodeRed.on('close', function() {
  server.close();
});
```

**Comment by pastukhov** [comment]
i'm getting
```javascript
18 Jun 09:27:06 - [error] [ifttt:d5935730.9bbb18] TypeError: Object function (params) {
  var handler, method, methodsHandlers, server, serverConfig;
  if (params == null) {
    params = {};
  }
  serverConfig = assign(config.server, params.server);
  debug('Initializing XMLRPC server with following config:', serverConfig);
  server = xmlrpc.createServer(serverConfig);
  methodsHandlers = assign(handlers(params), params.handlers);
  for (method in methodsHandlers) {
    handler = methodsHandlers[method];
    debug("Binding following handler to XMLRPC server method `" + method + "`:", handler);
    server.on(method, handler);
  }
  return server;
} has no method 'close'

```
But i'm seeing coffeescript for the first time.

**Comment by pastukhov** [comment]
Did you see https://ifttt.com/maker ?
No more  needed to look like wordpress!!
